CREATE TABLE IF NOT EXISTS USERS(

id SERIAL NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
user_name VARCHAR(50) UNIQUE NOT NULL,
age INTEGER NOT NULL,
birth_date DATE NOT NULL
)