apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - http:
        paths:
          - path: /ingress-age
            backend:
              serviceName: age-service
              servicePort: age-port
          - path: /ingress-user
            backend:
              serviceName: user-service
              servicePort: user-port
