apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - http:
        paths:
          - path: /idade
            backend:
              serviceName: age-service
              servicePort: 8091
          - path: /usuarios
            backend:
              serviceName: user-service
              servicePort: 8090
