apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-deployment
  template:
    metadata:
      labels:
        app: user-deployment

    spec:
      containers:
        - name: user-service
          imagePullPolicy: Never
          image: learning-k8s/user-service:1.0.3
          ports:
            - name: user-port
              containerPort: 8090

          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
